// System call numbers
#define SYS_fork              1
#define SYS_exit              2
#define SYS_wait              3
#define SYS_pipe              4
#define SYS_read              5
#define SYS_kill              6
#define SYS_exec              7
#define SYS_fstat             8
#define SYS_chdir             9
#define SYS_dup              10
#define SYS_getpid           11
#define SYS_sbrk             12
#define SYS_sleep            13
#define SYS_uptime           14
#define SYS_open             15
#define SYS_write            16
#define SYS_mknod            17
#define SYS_unlink           18
#define SYS_link             19
#define SYS_mkdir            20
#define SYS_close            21
#define SYS_getname          22
#define SYS_setname          23
#define SYS_getmaxproc       24
#define SYS_setmaxproc       25
#define SYS_getmaxmem        26
#define SYS_setmaxmem        27
#define SYS_getmaxdisk       28
#define SYS_setmaxdisk       29
#define SYS_getusedmem       30
#define SYS_setusedmem       31
#define SYS_getuseddisk      32
#define SYS_setuseddisk      33
#define SYS_setvc		     34
#define SYS_getvcfs		     35
#define SYS_setactivefs      36
#define SYS_getactivefs      37
#define SYS_getcwd           38
#define SYS_tostring         39
#define SYS_getactivefsindex 40
#define SYS_getatroot        41
#define SYS_setatroot        42
#define SYS_getpath          43
#define SYS_setpath          44
#define SYS_ps               45
#define SYS_getallusedmem	 46
#define SYS_setallusedmem    47
#define SYS_getallmaxmem     48
#define SYS_setallmaxmem     49
#define SYS_getalluseddisk   50
#define SYS_setalluseddisk   51
#define SYS_getallmaxdisk    52
#define SYS_setallmaxdisk    53
#define SYS_forkC 			 54
#define SYS_setalive		 55
#define SYS_getnumcontainers 56
#define SYS_getticks         57
#define SYS_cpause           58
#define SYS_cstop            59
#define SYS_cresume          60
#define SYS_setnextproc      61
